# Generated by Django 2.1 on 2018-09-06 04:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.TextField(max_length=256)),
                ('starting_date', models.DateField(default=datetime.datetime(2018, 9, 6, 4, 0, 35, 377423, tzinfo=utc))),
                ('ending_date', models.DateField(default=datetime.datetime(2018, 9, 6, 4, 0, 35, 387423, tzinfo=utc))),
                ('work_status', models.TextField(max_length=256)),
            ],
        ),
    ]
